In [120]:
import pandas as pd

In [121]:
matches = pd.read_csv("matches.csv", index_col = 0)

In [122]:
matches.head()

,date,time,comp,round,day,venue,result,gf,ga,opponent,...,match report,notes,sh,sot,dist,fk,pk,pkatt,season,team
1,2023-08-11,20:00,Premier League,Matchweek 1,Fri,Away,W,3,0,Burnley,...,Match Report,NaN,17.0,8.0,13.9,0.0,0,0,2022,Manchester City
3,2023-08-19,20:00,Premier League,Matchweek 2,Sat,Home,W,1,0,Newcastle Utd,...,Match Report,NaN,14.0,4.0,17.9,0.0,0,0,2022,Manchester City
4,2023-08-27,14:00,Premier League,Matchweek 3,Sun,Away,W,2,1,Sheffield Utd,...,Match Report,NaN,29.0,9.0,17.3,2.0,0,1,2022,Manchester City
5,2023-09-02,15:00,Premier League,Matchweek 4,Sat,Home,W,5,1,Fulham,...,Match Report,NaN,6.0,4.0,14.8,0.0,1,1,2022,Manchester City
6,2023-09-16,15:00,Premier League,Matchweek 5,Sat,Away,W,3,1,West Ham,...,Match Report,NaN,29.0,13.0,16.4,1.0,0,0,2022,Manchester City

In [123]:
matches.shape

(1520, 27)

In [124]:
matches.dtypes

date             object
time             object
comp             object
round            object
day              object
venue            object
result           object
gf                int64
ga                int64
opponent         object
xg              float64
xga             float64
poss            float64
attendance      float64
captain          object
formation        object
referee          object
match report     object
notes           float64
sh              float64
sot             float64
dist            float64
fk              float64
pk                int64
pkatt             int64
season            int64
team             object
dtype: object

In [125]:
matches["date"] = pd.to_datetime(matches["date"])

In [126]:
matches.dtypes

date            datetime64[ns]
time                    object
comp                    object
round                   object
day                     object
venue                   object
result                  object
gf                       int64
ga                       int64
opponent                object
xg                     float64
xga                    float64
poss                   float64
attendance             float64
captain                 object
formation               object
referee                 object
match report            object
notes                  float64
sh                     float64
sot                    float64
dist                   float64
fk                     float64
pk                       int64
pkatt                    int64
season                   int64
team                    object
dtype: object

In [127]:
matches["venue_code"] = matches["venue"].astype("category").cat.codes

In [128]:
matches["opp_code"] = matches["opponent"].astype("category").cat.codes

In [129]:
matches

,date,time,comp,round,day,venue,result,gf,ga,opponent,...,sh,sot,dist,fk,pk,pkatt,season,team,venue_code,opp_code
1,2023-08-11,20:00,Premier League,Matchweek 1,Fri,Away,W,3,0,Burnley,...,17.0,8.0,13.9,0.0,0,0,2022,Manchester City,0,5
3,2023-08-19,20:00,Premier League,Matchweek 2,Sat,Home,W,1,0,Newcastle Utd,...,14.0,4.0,17.9,0.0,0,0,2022,Manchester City,1,16
4,2023-08-27,14:00,Premier League,Matchweek 3,Sun,Away,W,2,1,Sheffield Utd,...,29.0,9.0,17.3,2.0,0,1,2022,Manchester City,0,18
5,2023-09-02,15:00,Premier League,Matchweek 4,Sat,Home,W,5,1,Fulham,...,6.0,4.0,14.8,0.0,1,1,2022,Manchester City,1,9
6,2023-09-16,15:00,Premier League,Matchweek 5,Sat,Away,W,3,1,West Ham,...,29.0,13.0,16.4,1.0,0,0,2022,Manchester City,0,21
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
42,2023-04-30,14:00,Premier League,Matchweek 34,Sun,Away,L,1,3,Newcastle Utd,...,4.0,3.0,17.3,0.0,0,0,2021,Southampton,0,16
43,2023-05-08,20:00,Premier League,Matchweek 35,Mon,Away,L,3,4,Nott'ham Forest,...,18.0,4.0,14.0,0.0,1,1,2021,Southampton,0,17
44,2023-05-13,15:00,Premier League,Matchweek 36,Sat,Home,L,0,2,Fulham,...,5.0,1.0,24.2,0.0,0,0,2021,Southampton,1,9
45,2023-05-21,14:00,Premier League,Matchweek 37,Sun,Away,L,1,3,Brighton,...,5.0,1.0,13.8,1.0,0,0,2021,Southampton,0,4
46,2023-05-28,16:30,Premier League,Matchweek 38,Sun,Home,D,4,4,Liverpool,...,15.0,10.0,17.5,1.0,0,0,2021,Southampton,1,12

In [130]:
matches["hour"] = matches["time"].str.replace(":.+", "", regex=True).astype("int")

In [131]:
matches["day_code"] = matches["date"].dt.dayofweek

In [132]:
matches

,date,time,comp,round,day,venue,result,gf,ga,opponent,...,dist,fk,pk,pkatt,season,team,venue_code,opp_code,hour,day_code
1,2023-08-11,20:00,Premier League,Matchweek 1,Fri,Away,W,3,0,Burnley,...,13.9,0.0,0,0,2022,Manchester City,0,5,20,4
3,2023-08-19,20:00,Premier League,Matchweek 2,Sat,Home,W,1,0,Newcastle Utd,...,17.9,0.0,0,0,2022,Manchester City,1,16,20,5
4,2023-08-27,14:00,Premier League,Matchweek 3,Sun,Away,W,2,1,Sheffield Utd,...,17.3,2.0,0,1,2022,Manchester City,0,18,14,6
5,2023-09-02,15:00,Premier League,Matchweek 4,Sat,Home,W,5,1,Fulham,...,14.8,0.0,1,1,2022,Manchester City,1,9,15,5
6,2023-09-16,15:00,Premier League,Matchweek 5,Sat,Away,W,3,1,West Ham,...,16.4,1.0,0,0,2022,Manchester City,0,21,15,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
42,2023-04-30,14:00,Premier League,Matchweek 34,Sun,Away,L,1,3,Newcastle Utd,...,17.3,0.0,0,0,2021,Southampton,0,16,14,6
43,2023-05-08,20:00,Premier League,Matchweek 35,Mon,Away,L,3,4,Nott'ham Forest,...,14.0,0.0,1,1,2021,Southampton,0,17,20,0
44,2023-05-13,15:00,Premier League,Matchweek 36,Sat,Home,L,0,2,Fulham,...,24.2,0.0,0,0,2021,Southampton,1,9,15,5
45,2023-05-21,14:00,Premier League,Matchweek 37,Sun,Away,L,1,3,Brighton,...,13.8,1.0,0,0,2021,Southampton,0,4,14,6
46,2023-05-28,16:30,Premier League,Matchweek 38,Sun,Home,D,4,4,Liverpool,...,17.5,1.0,0,0,2021,Southampton,1,12,16,6

In [133]:
matches["target"] = (matches["result"] == 'W').astype("int") #if the team wins, this boolean returns 1, else 0

In [134]:
from sklearn.ensemble import RandomForestClassifier

In [135]:
rf = RandomForestClassifier(n_estimators=400, min_samples_split=10, random_state=1)

In [136]:
train = matches[matches["date"] < '2023-01-01']

In [137]:
test = matches[matches["date"] > '2023-01-01']

In [138]:
predictors = ["venue_code", "opp_code", "hour", "day_code"]

In [139]:
rf.fit(train[predictors], train["target"])

RandomForestClassifier(min_samples_split=10, n_estimators=400, random_state=1)

In [140]:
preds = rf.predict(test[predictors])

In [141]:
from sklearn.metrics import accuracy_score

In [142]:
acc = accuracy_score(test["target"], preds)

In [143]:
acc

0.622895622895623

In [144]:
combined = pd.DataFrame(dict(actual = test["target"], prediction = preds))

In [145]:
pd.crosstab(index=combined["actual"], columns=combined["prediction"])

prediction    0    1
actual
0           574  151
1           297  166

In [146]:
from sklearn.metrics import precision_score

In [147]:
precision_score(test["target"], preds)

0.5236593059936908

In [148]:
grouped_matches = matches.groupby("team")

In [149]:
group = grouped_matches.get_group("Manchester City")

In [150]:
group

,date,time,comp,round,day,venue,result,gf,ga,opponent,...,fk,pk,pkatt,season,team,venue_code,opp_code,hour,day_code,target
1,2023-08-11,20:00,Premier League,Matchweek 1,Fri,Away,W,3,0,Burnley,...,0.0,0,0,2022,Manchester City,0,5,20,4,1
3,2023-08-19,20:00,Premier League,Matchweek 2,Sat,Home,W,1,0,Newcastle Utd,...,0.0,0,0,2022,Manchester City,1,16,20,5,1
4,2023-08-27,14:00,Premier League,Matchweek 3,Sun,Away,W,2,1,Sheffield Utd,...,2.0,0,1,2022,Manchester City,0,18,14,6,1
5,2023-09-02,15:00,Premier League,Matchweek 4,Sat,Home,W,5,1,Fulham,...,0.0,1,1,2022,Manchester City,1,9,15,5,1
6,2023-09-16,15:00,Premier League,Matchweek 5,Sat,Away,W,3,1,West Ham,...,1.0,0,0,2022,Manchester City,0,21,15,5,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
52,2023-05-06,15:00,Premier League,Matchweek 35,Sat,Home,W,2,1,Leeds United,...,2.0,0,1,2021,Manchester City,1,10,15,5,1
54,2023-05-14,14:00,Premier League,Matchweek 36,Sun,Away,W,3,0,Everton,...,2.0,0,0,2021,Manchester City,0,8,14,6,1
56,2023-05-21,16:00,Premier League,Matchweek 37,Sun,Home,W,1,0,Chelsea,...,0.0,0,0,2021,Manchester City,1,6,16,6,1
57,2023-05-24,20:00,Premier League,Matchweek 32,Wed,Away,D,1,1,Brighton,...,0.0,0,0,2021,Manchester City,0,4,20,2,0
58,2023-05-28,16:30,Premier League,Matchweek 38,Sun,Away,L,0,1,Brentford,...,0.0,0,0,2021,Manchester City,0,3,16,6,0

In [151]:
def rolling_averages(group, cols, new_cols):
    group = group.sort_values("date")
    rolling_stats = group[cols].rolling(3, closed = 'left').mean()
    group[new_cols] = rolling_stats
    group = group.dropna(subset = new_cols)
    return group

In [152]:
cols = ["gf", "ga", "sh", "sot", "dist", "fk", "pk", "pkatt"]
new_cols = [f"{c}_rolling" for c in cols]

In [153]:
new_cols

['gf_rolling',
 'ga_rolling',
 'sh_rolling',
 'sot_rolling',
 'dist_rolling',
 'fk_rolling',
 'pk_rolling',
 'pkatt_rolling']

In [154]:
rolling_averages(group, cols, new_cols)

,date,time,comp,round,day,venue,result,gf,ga,opponent,...,day_code,target,gf_rolling,ga_rolling,sh_rolling,sot_rolling,dist_rolling,fk_rolling,pk_rolling,pkatt_rolling
4,2022-08-27,15:00,Premier League,Matchweek 4,Sat,Home,W,4,2,Crystal Palace,...,5,1,3.000000,1.000000,17.666667,6.000000,17.466667,0.666667,0.333333,0.333333
5,2022-08-31,19:30,Premier League,Matchweek 5,Wed,Home,W,6,0,Nott'ham Forest,...,2,1,3.666667,1.666667,19.333333,7.333333,15.933333,0.333333,0.000000,0.000000
6,2022-09-03,17:30,Premier League,Matchweek 6,Sat,Away,D,1,1,Aston Villa,...,5,0,4.333333,1.666667,18.666667,8.000000,15.033333,0.333333,0.000000,0.000000
9,2022-09-17,12:30,Premier League,Matchweek 8,Sat,Away,W,3,0,Wolves,...,5,1,3.666667,1.000000,16.000000,6.000000,15.233333,0.333333,0.000000,0.000000
10,2022-10-02,14:00,Premier League,Matchweek 9,Sun,Home,W,6,3,Manchester Utd,...,6,1,3.333333,0.333333,15.333333,6.666667,17.000000,0.333333,0.000000,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
51,2024-04-28,16:30,Premier League,Matchweek 35,Sun,Away,W,2,0,Nott'ham Forest,...,6,1,4.333333,1.000000,22.666667,8.666667,16.666667,0.333333,0.333333,0.333333
52,2024-05-04,17:30,Premier League,Matchweek 36,Sat,Home,W,5,1,Wolves,...,5,1,3.666667,0.333333,20.333333,7.666667,17.533333,0.666667,0.333333,0.333333
53,2024-05-11,12:30,Premier League,Matchweek 37,Sat,Away,W,4,0,Fulham,...,5,1,3.666667,0.333333,14.333333,7.000000,17.000000,0.666667,0.666667,0.666667
54,2024-05-14,20:00,Premier League,Matchweek 34,Tue,Away,W,2,0,Tottenham,...,1,1,3.666667,0.333333,14.666667,7.666667,17.200000,0.333333,1.000000,1.000000
55,2024-05-19,16:00,Premier League,Matchweek 38,Sun,Home,W,3,1,West Ham,...,6,1,3.666667,0.333333,13.333333,7.333333,15.800000,0.000000,1.333333,1.333333

In [155]:
matches_rolling = matches.groupby("team").apply(lambda x: rolling_averages(x, cols, new_cols))

/var/folders/dw/d0q66w2s1sb87kwfcrbhzvk80000gn/T/ipykernel_1697/4052147919.py:1: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  matches_rolling = matches.groupby("team").apply(lambda x: rolling_averages(x, cols, new_cols))

In [156]:
matches_rolling

                                 date   time            comp         round  \
team
Arsenal                 3  2022-08-27  17:30  Premier League   Matchweek 4
                        4  2022-08-31  19:30  Premier League   Matchweek 5
                        5  2022-09-04  16:30  Premier League   Matchweek 6
                        7  2022-09-18  12:00  Premier League   Matchweek 8
                        8  2022-10-01  12:30  Premier League   Matchweek 9
...                               ...    ...             ...           ...
Wolverhampton Wanderers 40 2024-04-24  19:45  Premier League  Matchweek 29
                        41 2024-04-27  15:00  Premier League  Matchweek 35
                        42 2024-05-04  17:30  Premier League  Matchweek 36
                        43 2024-05-11  15:00  Premier League  Matchweek 37
                        44 2024-05-19  16:00  Premier League  Matchweek 38

                            day venue result  gf  ga         opponent  ...  \
team                                                                   ...
Arsenal                 3   Sat  Home      W   2   1           Fulham  ...
                        4   Wed  Home      W   2   1      Aston Villa  ...
                        5   Sun  Away      L   1   3   Manchester Utd  ...
                        7   Sun  Away      W   3   0        Brentford  ...
                        8   Sat  Home      W   3   1        Tottenham  ...
...                         ...   ...    ...  ..  ..              ...  ...
Wolverhampton Wanderers 40  Wed  Home      L   0   1      Bournemouth  ...
                        41  Sat  Home      W   2   1       Luton Town  ...
                        42  Sat  Away      L   1   5  Manchester City  ...
                        43  Sat  Home      L   1   3   Crystal Palace  ...
                        44  Sun  Away      L   0   2        Liverpool  ...

                            day_code  target  gf_rolling  ga_rolling  \
team
Arsenal                 3          5       1    3.000000    0.666667
                        4          2       1    3.000000    1.000000
                        5          6       0    2.333333    0.666667
                        7          6       1    1.666667    1.666667
                        8          5       1    2.000000    1.333333
...                              ...     ...         ...         ...
Wolverhampton Wanderers 40         2       0    1.000000    2.000000
                        41         5       1    0.666667    1.666667
                        42         5       0    0.666667    1.333333
                        43         5       0    1.000000    2.333333
                        44         6       0    1.333333    3.000000

                           sh_rolling sot_rolling dist_rolling fk_rolling  \
team
Arsenal                 3   14.333333    5.000000    14.133333   0.333333
                        4   18.333333    7.000000    14.433333   0.333333
                        5   19.333333    7.333333    15.533333   0.666667
                        7   20.000000    6.333333    16.800000   1.000000
                        8   17.000000    6.000000    17.700000   0.666667
...                               ...         ...          ...        ...
Wolverhampton Wanderers 40   9.666667    4.000000    20.533333   0.333333
                        41  10.333333    3.333333    18.766667   0.000000
                        42  11.000000    4.000000    19.666667   0.000000
                        43  10.000000    3.333333    15.966667   0.000000
                        44   9.666667    4.666667    14.133333   0.000000

                            pk_rolling  pkatt_rolling
team
Arsenal                 3     0.000000       0.000000
                        4     0.000000       0.000000
                        5     0.000000       0.000000
                        7     0.000000       0.000000
                        8     0.000000       0.000000
...                                ...            ...
Wolverhampton Wanderers 40    0.333333       0.333333
                        41    0.000000       0.000000
                        42    0.000000       0.000000
                        43    0.000000       0.000000
                        44    0.000000       0.000000

[1451 rows x 40 columns]

In [157]:
matches_rolling = matches_rolling.droplevel('team')

In [158]:
matches_rolling

,date,time,comp,round,day,venue,result,gf,ga,opponent,...,day_code,target,gf_rolling,ga_rolling,sh_rolling,sot_rolling,dist_rolling,fk_rolling,pk_rolling,pkatt_rolling
3,2022-08-27,17:30,Premier League,Matchweek 4,Sat,Home,W,2,1,Fulham,...,5,1,3.000000,0.666667,14.333333,5.000000,14.133333,0.333333,0.000000,0.000000
4,2022-08-31,19:30,Premier League,Matchweek 5,Wed,Home,W,2,1,Aston Villa,...,2,1,3.000000,1.000000,18.333333,7.000000,14.433333,0.333333,0.000000,0.000000
5,2022-09-04,16:30,Premier League,Matchweek 6,Sun,Away,L,1,3,Manchester Utd,...,6,0,2.333333,0.666667,19.333333,7.333333,15.533333,0.666667,0.000000,0.000000
7,2022-09-18,12:00,Premier League,Matchweek 8,Sun,Away,W,3,0,Brentford,...,6,1,1.666667,1.666667,20.000000,6.333333,16.800000,1.000000,0.000000,0.000000
8,2022-10-01,12:30,Premier League,Matchweek 9,Sat,Home,W,3,1,Tottenham,...,5,1,2.000000,1.333333,17.000000,6.000000,17.700000,0.666667,0.000000,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
40,2024-04-24,19:45,Premier League,Matchweek 29,Wed,Home,L,0,1,Bournemouth,...,2,0,1.000000,2.000000,9.666667,4.000000,20.533333,0.333333,0.333333,0.333333
41,2024-04-27,15:00,Premier League,Matchweek 35,Sat,Home,W,2,1,Luton Town,...,5,1,0.666667,1.666667,10.333333,3.333333,18.766667,0.000000,0.000000,0.000000
42,2024-05-04,17:30,Premier League,Matchweek 36,Sat,Away,L,1,5,Manchester City,...,5,0,0.666667,1.333333,11.000000,4.000000,19.666667,0.000000,0.000000,0.000000
43,2024-05-11,15:00,Premier League,Matchweek 37,Sat,Home,L,1,3,Crystal Palace,...,5,0,1.000000,2.333333,10.000000,3.333333,15.966667,0.000000,0.000000,0.000000
44,2024-05-19,16:00,Premier League,Matchweek 38,Sun,Away,L,0,2,Liverpool,...,6,0,1.333333,3.000000,9.666667,4.666667,14.133333,0.000000,0.000000,0.000000

In [159]:
matches_rolling.index = range(matches_rolling.shape[0])

In [160]:
matches_rolling

,date,time,comp,round,day,venue,result,gf,ga,opponent,...,day_code,target,gf_rolling,ga_rolling,sh_rolling,sot_rolling,dist_rolling,fk_rolling,pk_rolling,pkatt_rolling
0,2022-08-27,17:30,Premier League,Matchweek 4,Sat,Home,W,2,1,Fulham,...,5,1,3.000000,0.666667,14.333333,5.000000,14.133333,0.333333,0.000000,0.000000
1,2022-08-31,19:30,Premier League,Matchweek 5,Wed,Home,W,2,1,Aston Villa,...,2,1,3.000000,1.000000,18.333333,7.000000,14.433333,0.333333,0.000000,0.000000
2,2022-09-04,16:30,Premier League,Matchweek 6,Sun,Away,L,1,3,Manchester Utd,...,6,0,2.333333,0.666667,19.333333,7.333333,15.533333,0.666667,0.000000,0.000000
3,2022-09-18,12:00,Premier League,Matchweek 8,Sun,Away,W,3,0,Brentford,...,6,1,1.666667,1.666667,20.000000,6.333333,16.800000,1.000000,0.000000,0.000000
4,2022-10-01,12:30,Premier League,Matchweek 9,Sat,Home,W,3,1,Tottenham,...,5,1,2.000000,1.333333,17.000000,6.000000,17.700000,0.666667,0.000000,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1446,2024-04-24,19:45,Premier League,Matchweek 29,Wed,Home,L,0,1,Bournemouth,...,2,0,1.000000,2.000000,9.666667,4.000000,20.533333,0.333333,0.333333,0.333333
1447,2024-04-27,15:00,Premier League,Matchweek 35,Sat,Home,W,2,1,Luton Town,...,5,1,0.666667,1.666667,10.333333,3.333333,18.766667,0.000000,0.000000,0.000000
1448,2024-05-04,17:30,Premier League,Matchweek 36,Sat,Away,L,1,5,Manchester City,...,5,0,0.666667,1.333333,11.000000,4.000000,19.666667,0.000000,0.000000,0.000000
1449,2024-05-11,15:00,Premier League,Matchweek 37,Sat,Home,L,1,3,Crystal Palace,...,5,0,1.000000,2.333333,10.000000,3.333333,15.966667,0.000000,0.000000,0.000000
1450,2024-05-19,16:00,Premier League,Matchweek 38,Sun,Away,L,0,2,Liverpool,...,6,0,1.333333,3.000000,9.666667,4.666667,14.133333,0.000000,0.000000,0.000000

In [161]:
def make_predictions(matches, predictors):
    train = matches[matches["date"] < '2023-01-01']
    test = matches[matches["date"] > '2023-01-01']
    rf.fit(train[predictors], train["target"])
    preds = rf.predict(test[predictors])
    combined = pd.DataFrame(dict(actual = test["target"], prediction = preds), index=test.index)
    precision = precision_score(test["target"], preds)
    return combined, precision

In [162]:
combined, precision = make_predictions(matches_rolling, predictors + new_cols)

In [163]:
precision

0.5555555555555556

In [164]:
combined

      actual  prediction
13         0           1
14         1           1
15         1           1
16         0           0
17         0           1
...      ...         ...
1446       0           0
1447       1           0
1448       0           0
1449       0           0
1450       0           0

[1179 rows x 2 columns]

In [165]:
combined = combined.merge(matches_rolling[["date", "team", "opponent", "result"]], left_index=True, right_index=True)

In [166]:
combined

,actual,prediction,date,team,opponent,result
13,0,1,2023-01-03,Arsenal,Newcastle Utd,D
14,1,1,2023-01-15,Arsenal,Tottenham,W
15,1,1,2023-01-22,Arsenal,Manchester Utd,W
16,0,0,2023-02-04,Arsenal,Everton,L
17,0,1,2023-02-11,Arsenal,Brentford,D
...,...,...,...,...,...,...
1446,0,0,2024-04-24,Wolverhampton Wanderers,Bournemouth,L
1447,1,0,2024-04-27,Wolverhampton Wanderers,Luton Town,W
1448,0,0,2024-05-04,Wolverhampton Wanderers,Manchester City,L
1449,0,0,2024-05-11,Wolverhampton Wanderers,Crystal Palace,L
1450,0,0,2024-05-19,Wolverhampton Wanderers,Liverpool,L

In [167]:
class MissingDict(dict):
    __missing__ = lambda self, key: key

map_values = {
    "Brighton and Hove Albion": "Brighton",
    "Manchester United": "Manchester Utd",
    "Newcastle United": "Newcastle Utd",
    "West Ham United": "West Ham",
    "Wolverhampton Wanderers": "Wolves",
}
mapping = MissingDict(**map_values)

In [168]:
mapping["Wolverhampton Wanderers"] #checking if the mapping works properly

'Wolves'

In [169]:
combined["new_team"] = combined["team"].map(mapping)

In [171]:
combined

,actual,prediction,date,team,opponent,result,new_team
13,0,1,2023-01-03,Arsenal,Newcastle Utd,D,Arsenal
14,1,1,2023-01-15,Arsenal,Tottenham,W,Arsenal
15,1,1,2023-01-22,Arsenal,Manchester Utd,W,Arsenal
16,0,0,2023-02-04,Arsenal,Everton,L,Arsenal
17,0,1,2023-02-11,Arsenal,Brentford,D,Arsenal
...,...,...,...,...,...,...,...
1446,0,0,2024-04-24,Wolverhampton Wanderers,Bournemouth,L,Wolves
1447,1,0,2024-04-27,Wolverhampton Wanderers,Luton Town,W,Wolves
1448,0,0,2024-05-04,Wolverhampton Wanderers,Manchester City,L,Wolves
1449,0,0,2024-05-11,Wolverhampton Wanderers,Crystal Palace,L,Wolves
1450,0,0,2024-05-19,Wolverhampton Wanderers,Liverpool,L,Wolves

In [172]:
merged = combined.merge(combined, left_on=["date", "new_team"], right_on=["date", "opponent"]) #merging the dataframe with itself to remove discrepancies (see if the predictions match up from both sides)

In [173]:
merged

,actual_x,prediction_x,date,team_x,opponent_x,result_x,new_team_x,actual_y,prediction_y,team_y,opponent_y,result_y,new_team_y
0,0,1,2023-01-03,Arsenal,Newcastle Utd,D,Arsenal,0,0,Newcastle United,Arsenal,D,Newcastle Utd
1,1,1,2023-01-15,Arsenal,Tottenham,W,Arsenal,0,0,Tottenham Hotspur,Arsenal,L,Tottenham Hotspur
2,1,1,2023-01-22,Arsenal,Manchester Utd,W,Arsenal,0,0,Manchester United,Arsenal,L,Manchester Utd
3,0,0,2023-02-04,Arsenal,Everton,L,Arsenal,1,0,Everton,Arsenal,W,Everton
4,0,1,2023-02-11,Arsenal,Brentford,D,Arsenal,0,0,Brentford,Arsenal,D,Brentford
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1014,0,0,2024-04-24,Wolverhampton Wanderers,Bournemouth,L,Wolves,1,0,Bournemouth,Wolves,W,Bournemouth
1015,1,0,2024-04-27,Wolverhampton Wanderers,Luton Town,W,Wolves,0,0,Luton Town,Wolves,L,Luton Town
1016,0,0,2024-05-04,Wolverhampton Wanderers,Manchester City,L,Wolves,1,1,Manchester City,Wolves,W,Manchester City
1017,0,0,2024-05-11,Wolverhampton Wanderers,Crystal Palace,L,Wolves,1,1,Crystal Palace,Wolves,W,Crystal Palace
1018,0,0,2024-05-19,Wolverhampton Wanderers,Liverpool,L,Wolves,1,1,Liverpool,Wolves,W,Liverpool

In [174]:
merged[(merged["prediction_x"] == 1) & (merged["prediction_y"] == 0)]["actual_x"].value_counts()

actual_x
1    141
0    100
Name: count, dtype: int64